### ISSUE TITLE
Error setting up entry xxx.fbxos.fr for freebox_home

### ISSUE THREAD

**Issue by Najihel** [echauvet/freebox_home#3]
Hello,

Since few weeks, this integration doesn't work anymore with this debug logs :

```
2024-11-03 11:39:30.470 INFO (MainThread) [freebox_api.aiofreepybox] Read application authorization file
2024-11-03 11:39:30.520 INFO (MainThread) [freebox_api.access] Session opened
2024-11-03 11:39:30.520 INFO (MainThread) [freebox_api.access] Permissions: {'parental': True, 'contacts': True, 'explorer': True, 'tv': True, 'wdo': True, 'downloader': True, 'profile': True, 'camera': True, 'settings': True, 'calls': True, 'home': True, 'pvr': True, 'vm': True, 'player': True}
2024-11-03 11:39:31.334 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry <snip>.fbxos.fr for freebox_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/freebox_home/__init__.py", line 60, in async_setup_entry
    await router.update_all()
  File "/config/custom_components/freebox_home/router.py", line 79, in update_all
    await self.update_sensors()
  File "/config/custom_components/freebox_home/router.py", line 119, in update_sensors
    self.sensors_temperature[sensor["name"]] = sensor["value"]
                                               ~~~~~~^^^^^^^^^
KeyError: 'value'
```

## HASS :

- Core : 2024.10.4
- Supervisor : 2024.10.3
- Operating System : 13.2
- Interface utilisateur : 20241002.4

## Freebox
- HW : Delta / Freebox v7 (r1)
- Version : 4.8.15

Any advice ?

Thanks

**Comment by echauvet** [comment]
Hi Najihel,

The issue is corrected, please update your repo.
Eric
